// What Works — method library
// Content synthesized from The Holding Co's dementia knowledge wiki, which draws on
// the Alzheimer's Association, NIA, Alzheimer's Society (UK), NHS, Family Caregiver
// Alliance, Dementia UK, Teepa Snow, Pauline Boss, and peer-reviewed sources.
// Evidence labels are deliberately honest. Unverified statistics from the wiki were
// intentionally NOT used here.

export const TOPICS = [
  { id: 'communication', label: 'Talking & connecting', short: 'Talk', color: '#3f6276', wash: '#e8eef1', ink: '#2c4858',
    blurb: 'What to say — and not say — in the hard moments.' },
  { id: 'daily-care', label: 'Everyday care', short: 'Care', color: '#a9542f', wash: '#f4e7df', ink: '#8a4525',
    blurb: 'Bathing, dressing, eating, meds and the daily rhythm.' },
  { id: 'activities', label: 'Activity & purpose', short: 'Do', color: '#a37d2c', wash: '#f3ead4', ink: '#856425',
    blurb: 'Filling the day with things that still feel good.' },
  { id: 'sleep', label: 'Sleep & evenings', short: 'Rest', color: '#3a6b61', wash: '#e2ece8', ink: '#2c544c',
    blurb: 'Calmer evenings, fewer hard nights.' },
  { id: 'home', label: 'Home & safety', short: 'Home', color: '#5e7444', wash: '#e9edda', ink: '#4a5c35',
    blurb: 'Small changes to the home that prevent big problems.' },
  { id: 'caregiver', label: 'You, the caregiver', short: 'You', color: '#855a76', wash: '#efe3eb', ink: '#6c4860',
    blurb: 'Because you are a person in this too, not just the help.' },
]

export const STAGES = [
  { id: 'early', label: 'Early' },
  { id: 'middle', label: 'Middle' },
  { id: 'late', label: 'Late' },
]

export const EFFORTS = [
  { id: 'moment', label: 'In the moment', note: 'Use it right now, no setup' },
  { id: 'setup', label: 'Set up once', note: 'A bit of preparation, then easier' },
  { id: 'habit', label: 'Build a habit', note: 'Works by becoming routine' },
]

export const EVIDENCE = [
  { id: 'research', label: 'Research-backed', note: 'Supported by controlled or peer-reviewed studies' },
  { id: 'clinical', label: 'Clinical guidance', note: 'Recommended by major dementia organizations' },
  { id: 'caregiver', label: 'Caregiver-tested', note: 'Practice wisdom families report works' },
]

export const TOOLKINDS = {
  practice: { label: 'Practice this conversation', verb: 'Rehearse with an AI coach and get gentle feedback' },
  video: { label: 'Watch how it’s done', verb: 'See a short, vetted how-to video' },
  printable: { label: 'Get a printable', verb: 'Download a one-page version for the fridge or care team' },
  reminder: { label: 'Set a reminder', verb: 'Turn this into a gentle recurring nudge' },
  playlist: { label: 'Build a playlist', verb: 'Make a favorite-era playlist together' },
  checklist: { label: 'Run the checklist', verb: 'Walk through it step by step' },
}

// helper to keep authoring terse
const S = (label, url) => ({ label, url })

export const METHODS = [
  // ───────────────────────── COMMUNICATION ─────────────────────────
  {
    slug: 'meet-them-in-their-reality',
    n: 1,
    topic: 'communication',
    title: 'Agree, don’t argue — meet them where they are',
    summary: 'When what they believe isn’t true, let it go. Step into their reality instead of correcting it.',
    situations: [
      'She insists on something that isn’t true',
      'He’s confused about what year it is or who you are',
      'Correcting her makes everything worse',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Dementia damages the brain’s ability to reason and update beliefs from new facts. Presenting evidence or reminding someone they “already forgot” can’t persuade them — it just reads as an attack and triggers agitation. The reliable channel is emotion, not logic. This is the everyday form of Validation (Naomi Feil) and Teepa Snow’s Positive Approach to Care.',
    steps: [
      'Notice the urge to correct — and skip it. Winning the fact costs you the moment.',
      'Acknowledge the feeling underneath what they said ("You’re worried about your mother").',
      'Agree with the emotion, or gently change the subject or activity.',
      'Look separately for the unmet need driving it — hunger, pain, boredom, fear, needing the toilet.',
    ],
    say: ['“Tell me about her.”', '“That sounds important — let’s sort it out together.”'],
    dontSay: ['“That’s not true, remember?”', '“We talked about this already.”'],
    watchOut: ['Going along with a belief is for comfort and connection — never to trick someone into something that violates their wishes or dignity.'],
    tool: { kind: 'practice' },
    sources: [
      S('Alzheimer’s Association — Communication', 'https://www.alz.org/help-support/caregiving/daily-care/communications'),
      S('Validation responses (PMC)', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10864765/'),
      S('Teepa Snow — Positive Approach to Care', 'https://teepasnow.com/'),
    ],
    related: ['answer-the-feeling', 'i-want-to-go-home', 'should-i-tell-her'],
  },
  {
    slug: 'answer-the-feeling',
    n: 2,
    topic: 'communication',
    title: 'Answer the feeling, not the question',
    summary: 'For the question asked over and over, respond to the worry underneath it — calmly, the same way, every time.',
    situations: [
      'She asks the same question again and again',
      '“What time is my appointment?” — for the tenth time',
      'The repeating is driving me up the wall',
    ],
    stages: ['early', 'middle'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'They can’t retain the answer, so repetition is usually anxiety seeking reassurance — not forgetfulness to be fixed. “I already told you” shames them and raises the anxiety, which makes the question come faster.',
    steps: [
      'Give the same calm, warm answer each time, as if it were the first.',
      'Name and soothe the feeling: “You’re looking forward to seeing the doctor — I’ll take you, no need to worry.”',
      'Write the recurring answer on a whiteboard or note they can see, so they can check it themselves.',
      'Redirect to a small activity once the worry eases.',
    ],
    say: ['“It’s at 2, and I’ll drive you. You’re all set.”'],
    dontSay: ['“You just asked me that.”', '“I’ve told you five times.”'],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Repetition', 'https://www.alz.org/help-support/caregiving/stages-behaviors/repetition'),
      S('HopeHealth — Responding to repetitive behaviors', 'https://www.hopehealthco.org/blog/for-dementia-caregivers-4-tips-for-responding-to-repetitive-behaviors/'),
    ],
    related: ['meet-them-in-their-reality', 'one-idea-at-a-time'],
  },
  {
    slug: 'i-want-to-go-home',
    n: 3,
    topic: 'communication',
    title: 'When they say “I want to go home” — and they’re already home',
    summary: '“Home” is usually a feeling of safety, not an address. Soothe the feeling instead of debating the place.',
    situations: [
      'He keeps asking to go home when he is home',
      'She doesn’t recognize the house as hers',
      'Packing a bag to “leave,” especially late in the day',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: '“Home” often means a time and a feeling — childhood, security, a place where everything made sense — not the current building, which they may genuinely not recognize. Insisting “you ARE home” argues with a feeling and loses.',
    steps: [
      'Validate the longing: “I know you want to be home.”',
      'Reassure and buy time with a small comfort — a cup of tea, sitting together.',
      'Redirect into a memory: “Tell me about home — what was your favorite room?”',
      'Check for the unmet need — tired, needing the toilet, overstimulated, scared as light fades.',
    ],
    say: ['“Let’s have a cup of tea first, then we’ll sort it out.”', '“Tell me about home.”'],
    dontSay: ['“You ARE home.”', '“We sold that house years ago.”'],
    tool: { kind: 'practice' },
    sources: [
      S('Alzheimer’s Society (UK) — “I want to go home”', 'https://www.alzheimers.org.uk/blog/i-want-go-home-what-to-say-to-someone-in-dementia-care'),
      S('AgingCare — “I just want to go home”', 'https://www.agingcare.com/articles/what-to-do-when-elderly-parents-wants-to-leave-the-nursing-home-138005.htm'),
    ],
    related: ['meet-them-in-their-reality', 'calm-the-evening'],
  },
  {
    slug: 'false-accusation',
    n: 4,
    topic: 'communication',
    title: 'When they accuse you of stealing or lying',
    summary: 'The accusation is a symptom, not a verdict. Don’t defend yourself — join their side and help “find” it.',
    situations: [
      'She says I stole her purse / money / ring',
      'He thinks I’m poisoning him or keeping him prisoner',
      'I feel hurt and furious at being accused',
    ],
    stages: ['middle'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'A misplaced item plus a memory gap becomes “someone took it.” It is the brain filling a blank — not a real belief about you. Defending yourself reads as guilt and escalates. It is not personal, even though it feels deeply personal.',
    steps: [
      'Don’t argue or defend. Take a breath; remind yourself it’s the disease.',
      'Validate the upset: “That’s so frustrating — let’s look for it together.”',
      'Help them “find” it, calmly.',
      'Keep duplicates of frequently-lost items (glasses, wallet) to defuse the next time.',
    ],
    say: ['“Let’s look for it together.”'],
    dontSay: ['“I would never steal from you.”', '“Nobody took it, you lost it.”'],
    watchOut: ['A sudden surge in suspicion or confusion can signal a UTI or other illness — worth a medical check.'],
    tool: { kind: 'practice' },
    sources: [
      S('DailyCaring — Dealing with false accusations', 'https://dailycaring.com/8-ways-to-deal-with-false-dementia-accusations/'),
      S('Alzheimer’s Society (UK) — False accusations', 'https://www.alzheimers.org.uk/get-support/publications-and-factsheets/dementia-together/advice-dealing-false-accusations-dementia'),
    ],
    related: ['meet-them-in-their-reality', 'externalize-the-disease'],
  },
  {
    slug: 'asking-for-someone-who-died',
    n: 5,
    topic: 'communication',
    title: 'When they ask for someone who has died',
    summary: 'Re-telling the death can re-break their heart each time. Lead with memory; use a gentle fib only if the truth causes real distress.',
    situations: [
      'She asks where her husband is — he passed years ago',
      'He wants to visit his mother',
      'Telling the truth makes her grieve all over again',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'If they can’t retain the death, each telling lands as fresh, brand-new grief. The kind move is usually to answer the longing behind the question rather than re-deliver the loss. See the decision rubric in “Should I tell her?”',
    steps: [
      'Redirect to memory first: “Tell me about him — what made you laugh?”',
      'If the truth would cause real, repeating distress, use a gentle “fiblet”: “She’s gone to the shop, back later — shall we look at photos while we wait?”',
      'Sit with the feeling; offer presence over facts.',
    ],
    say: ['“Tell me about her.”', '“He’ll be back later — let’s look at these photos.”'],
    dontSay: ['“He died ten years ago, remember?”'],
    watchOut: ['In the early stage, when the person can still hold and process the truth, honesty (gently) is usually right. Fiblets are for when truth only re-inflicts pain.'],
    tool: { kind: 'practice' },
    sources: [
      S('AARP — Therapeutic fibbing', 'https://www.aarp.org/caregiving/medical/therapeutic-fibbing-dementia-communication/'),
    ],
    related: ['should-i-tell-her', 'meet-them-in-their-reality'],
  },
  {
    slug: 'should-i-tell-her',
    n: 6,
    topic: 'communication',
    title: 'The “Should I tell her the truth?” rubric',
    summary: 'Four quick questions that turn an agonizing one-off decision into a calm, repeatable judgment.',
    situations: [
      'I don’t know whether to tell her the hard truth',
      'I feel guilty about lying to my parent',
      'Is it okay to not correct him?',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Truth is the default; comfort is the constraint. The Alzheimer’s Society frames an outright lie as a “least-bad” option, justified only when anything else would cause significant harm — used sparingly, “like antipsychotics.” So the real question is how far down the spectrum you need to go: whole truth → gentle/partial truth → redirection → going along → a protective fib.',
    steps: [
      'Purpose: Whose comfort is this for? If the truth serves no decision, safety, or right of theirs, you may not need to raise it.',
      'Harm: What does the truth cost here and now — lasting distress, or just momentary discomfort? Manageable discomfort isn’t a reason to lie.',
      'Retention: Will they hold onto it? If not, a painful truth is just re-inflicted as fresh grief each time.',
      'Redirect: Can distraction or answering the emotion defuse it without any untruth? Very often, yes.',
    ],
    watchOut: [
      'Lie outright only when purpose is low AND harm of truth is high and repeating AND retention is low AND nothing else works.',
      'Agree the family “story” so the person isn’t told contradictory things by different people.',
      'Caregiver guilt is normal and is not evidence you did wrong.',
    ],
    tool: { kind: 'practice' },
    sources: [
      S('Alzheimer’s Society (UK) — Is it okay to lie?', 'https://www.alzheimers.org.uk/blog/lying-to-someone-with-dementia'),
      S('AARP — Therapeutic fibbing', 'https://www.aarp.org/caregiving/medical/therapeutic-fibbing-dementia-communication/'),
    ],
    related: ['asking-for-someone-who-died', 'meet-them-in-their-reality'],
  },
  {
    slug: 'talk-to-me-not-about-me',
    n: 7,
    topic: 'communication',
    title: 'Talk to them, not about them',
    summary: 'In the doctor’s office and at the dinner table, keep the person in the conversation about their own life.',
    situations: [
      'Doctors talk to me instead of to her',
      'People speak over him as if he isn’t there',
      'I catch myself answering for her',
    ],
    stages: ['early', 'middle'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Being talked about, not to, is a recognized and painful disempowerment — “nothing about me without me.” Including the person protects their sense of self (personhood) and often gets you better information, too.',
    steps: [
      'Let the person answer first, unless they’ve asked you to speak for them.',
      'Redirect questions back to them: “Mom, the doctor asked how you’ve been sleeping — what would you say?”',
      'In appointments, sit so they’re included; step out if they want privacy with the clinician.',
    ],
    say: ['“Mom, what would you say?”'],
    dontSay: ['(to the doctor, over them) “She doesn’t really know what day it is.”'],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Working with the doctor', 'https://www.alz.org/help-support/caregiving/daily-care/working-with-the-doctor'),
      S('NIA — Going to the doctor', 'https://www.nia.nih.gov/health/medical-care-and-appointments/taking-someone-doctors-appointment-tips-caregivers'),
    ],
    related: ['externalize-the-disease', 'capture-her-life-story'],
  },
  {
    slug: 'externalize-the-disease',
    n: 8,
    topic: 'communication',
    title: 'Blame the disease, out loud',
    summary: 'A short, warm reassurance that takes the shame off them — and, quietly, off you.',
    situations: [
      'She’s ashamed and blames herself for forgetting',
      'He gets embarrassed and withdraws',
      'I get angry and then feel terrible about it',
    ],
    stages: ['early', 'middle'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Dementia carries heavy stigma that people turn inward as shame and self-blame. Externalizing the illness — “this is the disease, not you” — is a recognized way to reduce that shame and protect self-worth. The same message helps you: your frustration is not a failure of love.',
    steps: [
      'Keep reassurance short, warm, and concrete: “This isn’t your fault — it’s a disease happening to you. I’ve got you.”',
      'Don’t call attention to mistakes; let small ones pass.',
      'Say it to yourself, too, when you snap: it’s the disease, not your failing.',
    ],
    say: ['“It’s not you — it’s the illness. We’ll figure it out together.”'],
    dontSay: ['“How could you forget that?”'],
    tool: { kind: 'practice' },
    sources: [
      S('Managing shame & stigma in dementia (PubMed)', 'https://pubmed.ncbi.nlm.nih.gov/30866693/'),
      S('Alzheimer’s Association — Communication', 'https://www.alz.org/help-support/caregiving/daily-care/communications'),
    ],
    related: ['talk-to-me-not-about-me', 'hold-both-and'],
  },
  {
    slug: 'one-idea-at-a-time',
    n: 9,
    topic: 'communication',
    title: 'One idea at a time',
    summary: 'The everyday grammar of being understood: short sentences, simple choices, from the front, unhurried.',
    situations: [
      'My instructions seem to overwhelm him',
      'Open questions make her anxious',
      'Getting out the door is a daily battle',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'As dementia advances, holding several ideas at once gets harder. Long sentences and open questions overload; one simple idea, paired with a gesture, lands. This is the foundation under almost every other method here.',
    steps: [
      'Approach from the front, at eye level; say their name; use a calm voice.',
      'One short sentence, one step: “Let’s wash your hands,” not “Let’s get cleaned up for dinner.”',
      'Offer either/or choices, not open ones: “Blue shirt or green?” instead of “What do you want to wear?”',
      'Pair words with a gesture or demonstration; allow extra time to respond.',
    ],
    say: ['“Here’s your cup.” (holding it out)'],
    dontSay: ['“Do you remember what we need to do before we leave?”'],
    tool: { kind: 'printable' },
    sources: [
      S('Harvard Health — Dementia communication strategies', 'https://www.health.harvard.edu/mind-and-mood/bridging-the-gap-dementia-communication-strategies'),
      S('Alzheimer’s Association — Communication', 'https://www.alz.org/help-support/caregiving/daily-care/communications'),
    ],
    related: ['break-into-steps', 'hand-under-hand'],
  },

  // ───────────────────────── DAILY CARE ─────────────────────────
  {
    slug: 'warm-the-bathroom',
    n: 10,
    topic: 'daily-care',
    title: 'Warm the room and prep everything before a bath',
    summary: 'Most bathing refusal is about cold, fear, and exposure. Remove those before they ever undress.',
    situations: [
      'She refuses to shower or bathe',
      'He fights every bath',
      'Bath time is the worst part of our day',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Bathing stacks up everything hard at once — undressing in front of someone, cold air, water on the skin, loss of control, and no understanding of why. Sensory changes can make water feel genuinely cold or assaulting. Refusal is communication: usually fear, cold, or embarrassment, not defiance.',
    steps: [
      'Warm the room first; warm the towels and a robe.',
      'Lay out everything and draw the water (temperature-checked) before they come in, so time spent exposed and waiting is minimal.',
      'Cover them with a towel while undressing and between washing areas.',
      'Keep talk short and positive — focus on what comes after (“then we’ll have your coffee”), not on how long it’s been.',
      'Have soothing music ready, and be willing to pause and come back.',
    ],
    watchOut: ['A daily full shower is rarely necessary. Once or twice a week, with sponge baths between, is often plenty.'],
    tool: { kind: 'video' },
    sources: [
      S('NIA — Bathing, dressing & grooming', 'https://www.nia.nih.gov/health/alzheimers-caregiving/alzheimers-caregiving-bathing-dressing-and-grooming'),
      S('Alzheimer’s Association — Bathing', 'https://www.alz.org/help-support/caregiving/daily-care/bathing'),
      S('Family Caregiver Alliance — Bathing', 'https://www.caregiver.org/resource/bathing-dementia/'),
    ],
    related: ['lets-wash-up', 'hand-under-hand', 'add-contrast'],
  },
  {
    slug: 'lets-wash-up',
    n: 11,
    topic: 'daily-care',
    title: '“Let’s freshen up” — and keep a sponge bath in your back pocket',
    summary: 'Soften the language and lower the bar. A clean, dignified person matters more than a full daily shower.',
    situations: [
      'The word “bath” or “shower” triggers a fight',
      'A full shower is too much for him today',
      'I’m worried about hygiene but can’t win the shower battle',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'The goal is a clean, safe, dignified person — not immersion at any cost. Gentler framing and a lower-stakes option remove the power struggle, and a sponge or bed bath keeps someone clean on days a shower is too much.',
    steps: [
      'Say “let’s get you freshened up and warm,” not “you need a bath.”',
      'Let them hold the washcloth and do their own face; start with hands and feet.',
      'On hard days, do a sponge bath — face, hands, underarms, groin, feet — and no-rinse products between full washes.',
      'Match the helper to their comfort (often a same-sex helper for intimate care).',
    ],
    say: ['“Let’s get you freshened up — I’ve warmed a towel. You hold this.”'],
    dontSay: ['“You have to shower, you smell.”'],
    tool: { kind: 'video' },
    sources: [
      S('Alzheimer’s Association — Bathing', 'https://www.alz.org/help-support/caregiving/daily-care/bathing'),
      S('Dementia Careblazers — Refusing to bathe', 'https://careblazers.com/dementia-refuses-to-bathe-how-to-help/'),
    ],
    related: ['warm-the-bathroom', 'one-idea-at-a-time'],
  },
  {
    slug: 'hand-under-hand',
    n: 12,
    topic: 'daily-care',
    title: 'Hand-under-hand to start a stalled task',
    summary: 'When words fail, guide the motion through touch — and let muscle memory take over.',
    situations: [
      'He freezes partway through a task',
      'She won’t pick up the spoon / toothbrush',
      'Telling them what to do isn’t landing',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'A gentle guiding technique (associated with Teepa Snow’s Positive Approach to Care): slide your hand under theirs and guide the movement — lifting a spoon, moving a brush. It transmits what to do through touch when words can’t, while leaving the person feeling in control. Once the motion starts, deeply-learned muscle memory often carries them.',
    steps: [
      'Put what they need into their hand (spoon, brush, cloth).',
      'Slide your hand under theirs — not over and controlling — and begin the motion together.',
      'Ease off as the deeply-learned movement takes over.',
      'Pair with one calm cue at a time; never rush.',
    ],
    tool: { kind: 'video' },
    sources: [
      S('NursePartners — Hand-under-hand approach', 'https://nursepartners.org/understanding-alzheimers-dementias-hand-hand-approach/'),
      S('Teepa Snow — Positive Approach to Care', 'https://teepasnow.com/'),
    ],
    related: ['break-into-steps', 'side-by-side-brushing', 'one-idea-at-a-time'],
  },
  {
    slug: 'break-into-steps',
    n: 13,
    topic: 'daily-care',
    title: 'Break the task into single steps',
    summary: 'A multi-step task overwhelms; a sequence of one-step cues doesn’t. Help only the parts they can’t do.',
    situations: [
      'Getting dressed / brushing teeth stalls out',
      'He used to do this himself and now can’t start',
      'I end up taking over the whole thing',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'The obstacle is usually sequencing or initiation, not unwillingness. Decomposing the task and cueing one step at a time lets the person do every part they still can — and supervision and set-up preserve far more ability than taking over.',
    steps: [
      'Decompose it: “pick up the toothbrush” → “put it to your teeth” → “brush up and down.”',
      'Give one step, wait for it to finish, then cue the next.',
      'Lay tools out in order; pre-load (toothpaste on the brush, one food on the plate).',
      'Assist the hard parts only; let them keep the rest.',
    ],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Activities', 'https://www.alz.org/help-support/caregiving/daily-care/activities'),
      S('Elder Care Alliance — Communication tips', 'https://eldercarealliance.org/blog/10-tips-communicating-individuals-dementia/'),
    ],
    related: ['hand-under-hand', 'lay-out-clothes', 'one-food-at-a-time'],
  },
  {
    slug: 'lay-out-clothes',
    n: 14,
    topic: 'daily-care',
    title: 'Lay out one outfit, in the order it goes on',
    summary: 'Cut the closet down to a single decision and a clear sequence, and let them dress themselves longer.',
    situations: [
      'She can’t decide what to wear',
      'He puts clothes on backwards or in the wrong order',
      'Dressing has become a daily flashpoint',
    ],
    stages: ['early', 'middle'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Dressing is a long chain of choices and fine-motor steps, so it fails early. Too many options paralyze; the wrong order confuses. Removing the choices and pre-sequencing the garments preserves independence and self-image.',
    steps: [
      'Offer two options (“blue or green?”) or lay out a single outfit.',
      'Stack the clothes in the order they go on, and hand them over one at a time.',
      'Switch to adaptive clothing — elastic waists, Velcro, pullovers, slip-on shoes; avoid tiny buttons, back zips, laces.',
      'Don’t fight the same outfit every day — buy duplicates.',
    ],
    tool: { kind: 'printable' },
    sources: [
      S('NIA — Bathing, dressing & grooming', 'https://www.nia.nih.gov/health/alzheimers-caregiving/alzheimers-caregiving-bathing-dressing-and-grooming'),
      S('Alzheimer’s Association — Daily care plan', 'https://www.alz.org/help-support/caregiving/daily-care/daily-care-plan'),
    ],
    related: ['break-into-steps', 'scheduled-toileting'],
  },
  {
    slug: 'side-by-side-brushing',
    n: 15,
    topic: 'daily-care',
    title: 'Brush your teeth side by side',
    summary: 'Mirror the motion instead of doing it “to” them — and protect a mouth that can’t report its own pain.',
    situations: [
      'She won’t let me brush her teeth',
      'He no longer recognizes the toothbrush',
      'I think a sore tooth is making him miserable',
    ],
    stages: ['middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'Poor mouth health causes pain a person often can’t tell you about, which then drives refusing food and agitation. Brushing alongside them — so they copy you — turns care “done to” them into something shared, and gets the motion started.',
    steps: [
      'Pick the calmest time of day; it doesn’t have to be the bathroom — wherever they’re relaxed, sitting up with a towel on the chest.',
      'Hand over a brush with paste already on it; use an easy-grip or electric brush (the weight steadies tremor).',
      'Brush your own teeth next to them so they mirror you; or stand behind and guide hand-over-hand.',
      'Gently cover teeth, gums, tongue, and palate; clean dentures daily and check fit.',
    ],
    watchOut: ['New agitation, refusing food, or pulling at the mouth can mean a sore tooth or ill-fitting denture — get it checked.'],
    tool: { kind: 'video' },
    sources: [
      S('Alzheimer’s Association — Dental care', 'https://www.alz.org/help-support/caregiving/daily-care/dental-care'),
      S('Alzheimer’s Society (UK) — Healthy mouth', 'https://www.alzheimers.org.uk/get-support/living-with-dementia/supporting-person-dementia-keep-healthy-mouth'),
    ],
    related: ['hand-under-hand', 'break-into-steps'],
  },
  {
    slug: 'one-food-at-a-time',
    n: 16,
    topic: 'daily-care',
    title: 'Serve one or two foods at a time',
    summary: 'A full plate is a decision they can’t make. Simplify the plate, slow the meal, and eat together.',
    situations: [
      'She won’t eat / pushes the plate away',
      'A full plate seems to overwhelm him',
      'Mealtimes are stressful and rushed',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Eating problems are very common and risk weight loss and dehydration. A busy plate and a noisy room overwhelm; deciding among foods is hard; and apraxia can scramble how to use utensils. Simplifying the choice and the setting brings the appetite back.',
    steps: [
      'Serve one or two items at a time on a plain plate that contrasts with the food and table.',
      'Cut noise and clutter; allow up to an hour and don’t rush.',
      'Eat together so they can copy your motions; offer favorite foods and several small meals over the day.',
      'Switch to finger foods when utensils get hard; offer drinks all day, since thirst cues fade.',
    ],
    watchOut: ['Coughing, throat-clearing, a wet/gurgly voice, or pocketing food can signal swallowing trouble (dysphagia) — have a speech-language pathologist evaluate. Keep them upright, head slightly forward, while eating.'],
    tool: { kind: 'checklist' },
    sources: [
      S('Alzheimer’s Association — Food & eating', 'https://www.alz.org/help-support/caregiving/daily-care/food-eating'),
      S('NIA — Eating well', 'https://www.nia.nih.gov/health/alzheimers-caregiving/tips-caregivers-helping-people-alzheimers-disease-eat-well'),
    ],
    related: ['add-contrast', 'anchor-the-day'],
  },
  {
    slug: 'scheduled-toileting',
    n: 17,
    topic: 'daily-care',
    title: 'Offer the toilet on a schedule, before they ask',
    summary: 'Most accidents are about timing and finding the toilet — not lost control. A clock-based routine prevents many.',
    situations: [
      'Accidents are becoming frequent',
      'He can’t tell me in time that he needs to go',
      'I want to keep her dignity intact',
    ],
    stages: ['middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'Much incontinence is functional — the person can’t find, recognize, reach, or undress for the toilet in time, or can’t say they need to. Prompting on a schedule, and reading the non-verbal cues, prevents a large share of accidents and protects dignity.',
    steps: [
      'Prompt every ~2 hours and after meals, rather than waiting to be asked; tighten the interval if accidents fall between trips.',
      'Watch for the signals — restlessness, fidgeting, pacing, tugging at clothes — and respond immediately.',
      'Use easy clothing (elastic, Velcro) so the steps are fast.',
      'Limit fluids after dinner (not during the day) and cut evening caffeine to ease nights.',
    ],
    watchOut: ['A sudden onset or sharp worsening of incontinence — often with a spike in confusion — can be a UTI or constipation. Get it checked promptly.'],
    tool: { kind: 'reminder' },
    sources: [
      S('Alzheimer’s Association — Incontinence', 'https://www.alz.org/help-support/caregiving/daily-care/incontinence'),
      S('Family Caregiver Alliance — Incontinence', 'https://www.caregiver.org/resource/incontinence-dementia/'),
    ],
    related: ['make-the-toilet-findable', 'lay-out-clothes'],
  },
  {
    slug: 'find-the-reason-for-refused-meds',
    n: 18,
    topic: 'daily-care',
    title: 'When they refuse medication, find the reason first',
    summary: 'Refusal almost always has a fixable cause underneath. Look for it before you push — and never force.',
    situations: [
      'He spits out or hides his pills',
      'She thinks the medicine is poison',
      'Getting meds in is a daily fight',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Refusal usually traces to something solvable — can’t swallow the pill, feels sick, doesn’t trust it, paranoia, or unpleasant side effects. Forcing escalates and poisons every future attempt.',
    steps: [
      'Ask gently: “I can see you don’t want these — can you tell me why?”',
      'If refused, stop and try again in about 15 minutes rather than forcing.',
      'Anchor doses to mealtimes and the daily routine; let them do what they can.',
      'Ask the prescriber to simplify the regimen, and about liquid, patch, or dissolvable forms if swallowing is the problem.',
    ],
    watchOut: ['Never crush a pill or hide it in food without checking with the pharmacist that it’s safe to crush and that covert dosing is appropriate. Lock all medications away as judgment declines.'],
    tool: { kind: 'reminder' },
    sources: [
      S('BrightFocus — When a loved one refuses medications', 'https://www.brightfocus.org/resource/when-a-loved-one-refuses-to-take-alzheimers-medications-7-tips-for-the-caregiver/'),
      S('Family caregiver medication-refusal strategies (PMC)', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12762047/'),
    ],
    related: ['find-the-reason-for-refused-meds', 'anchor-the-day', 'meet-them-in-their-reality'],
  },
  {
    slug: 'anchor-the-day',
    n: 19,
    topic: 'daily-care',
    title: 'Anchor the day to a few fixed points',
    summary: 'Predictability is one of the most powerful, lowest-cost tools you have. Build a rhythm, not a timetable.',
    situations: [
      'Every task is a fresh negotiation',
      'He’s anxious and disoriented through the day',
      'I don’t know how to structure our days',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'A predictable routine supplies the structure the person can no longer generate internally, which lowers anxiety, agitation, and disorientation. When the next thing is always the same, they don’t have to decide, remember, or be persuaded — and deeply-learned habits carry them through tasks they couldn’t plan from scratch.',
    steps: [
      'Fix the anchors first: same wake time, same meals, same bedtime. Hang everything else off them.',
      'Honor their lifelong habits and chronotype — a morning bather resists an evening bath.',
      'Schedule demanding tasks (bathing, appointments) for their best window, often mid-morning.',
      'Use visible cues — a big clock, a day/date display, a whiteboard schedule — so they can orient without asking.',
      'Keep it flexible, not rigid; adjust as ability changes.',
    ],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Daily care plan', 'https://www.alz.org/help-support/caregiving/daily-care/daily-care-plan'),
      S('Where You Live Matters — Importance of routine', 'https://www.whereyoulivematters.org/resources/importance-of-routines-for-dementia/'),
    ],
    related: ['start-the-activity-for-them', 'calm-the-evening', 'morning-light'],
  },

  // ───────────────────────── ACTIVITIES ─────────────────────────
  {
    slug: 'start-the-activity-for-them',
    n: 20,
    topic: 'activities',
    title: 'Start the activity for them',
    summary: 'When someone “won’t do anything,” the problem is usually that they can’t begin. Lower the activation energy — you start, they join.',
    situations: [
      'She just sits and stares / sleeps all day',
      'He says no to everything I suggest',
      'Nothing seems to interest her anymore',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Apathy and loss of initiation are symptoms of the dementia itself — the brain machinery to plan, start, and follow through is damaged, even for things they’d enjoy. The answer is rarely persuasion; it’s to do the set-up and the first step, then invite them in. Pushing harder backfires.',
    steps: [
      'Do the set-up and begin the activity yourself — fold the first towel, start the music, lay out the cards.',
      'Invite, don’t ask: “Could you help me with these?” beats “Do you want to do an activity?”',
      'Hand over after you’ve started; break it into single steps.',
      'Read the signs — fading attention or rising frustration means modify or pause and try later.',
    ],
    watchOut: ['Apathy can look like depression, but depression brings sadness, tearfulness, and sleep/appetite change, and is treatable — flag it to the doctor.'],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Activities', 'https://www.alz.org/help-support/caregiving/daily-care/activities'),
      S('Dementia UK — Meaningful activities', 'https://www.dementiauk.org/news/meaningful-activities-for-a-person-with-dementia/'),
    ],
    related: ['failure-free-activity', 'make-them-needed', 'anchor-the-day'],
  },
  {
    slug: 'failure-free-activity',
    n: 21,
    topic: 'activities',
    title: 'Build a “can’t-fail” activity from an old role',
    summary: 'Take something they did well for decades, strip it to one safe step at a time, and let their hands remember.',
    situations: [
      'Activities frustrate or embarrass him now',
      'I want to give her something to do that feels real',
      'Generic “activities” feel like babysitting',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'setup',
    evidence: 'research',
    why: 'Failure-free, Montessori-based activity is designed so the person cannot fail — drawn from their past interests and roles, broken into clear steps, using real (not childish) materials. In controlled studies, Montessori-based programming produced markedly more constructive engagement and less apathy than standard activity programming.',
    steps: [
      'Pick something they did competently for years — a former office worker sorting and assembling; a homemaker folding laundry or setting the table; a gardener potting plants.',
      'Strip it to a safe, single-step-at-a-time version; lay the materials out in order.',
      'Use adult, dignified materials — folding, sorting, polishing, simple food prep, winding yarn, matching tasks.',
      'Let them lead; the point is engagement, not a “correct” result.',
    ],
    watchOut: ['Never infantilize. Use grown-up materials and framing — the aim is competence and contribution, not busywork that signals “you’re a child.”'],
    tool: { kind: 'printable' },
    sources: [
      S('DementiaCareCentral — Montessori method', 'https://www.dementiacarecentral.com/dementiacare/montessori-method'),
      S('Montessori engagement study (PMC)', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2685273/'),
    ],
    related: ['start-the-activity-for-them', 'make-them-needed', 'capture-her-life-story'],
  },
  {
    slug: 'make-them-needed',
    n: 22,
    topic: 'activities',
    title: 'Make them needed — “Could you help me?”',
    summary: 'Purpose beats entertainment. Folding the towels “wrong” together is worth more than a perfect job done alone.',
    situations: [
      'He seems to have lost his sense of usefulness',
      'She gets restless and underfoot',
      'I want activities that mean something, not just fill time',
    ],
    stages: ['early', 'middle'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'Engagement, not achievement, is the point. Being asked to help gives a sense of purpose and success; involvement in real household life maintains identity. Process matters more than result — it doesn’t matter if the towels are folded “right.”',
    steps: [
      'Frame tasks as helping you: “Could you help me with these?”',
      'Channel restless energy into a job — hand them a cloth to wipe the table, socks to pair, a bowl to stir.',
      'Don’t correct or criticize the result; thank them for the help.',
      'Watch what they start on their own and build those into the day.',
    ],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Activities', 'https://www.alz.org/help-support/caregiving/daily-care/activities'),
    ],
    related: ['start-the-activity-for-them', 'failure-free-activity'],
  },
  {
    slug: 'favorite-era-playlist',
    n: 23,
    topic: 'activities',
    title: 'Make a favorite-era playlist',
    summary: 'Music from their teens and twenties reaches past the disease. Keep it cued for hard moments and quiet afternoons.',
    situations: [
      'He’s agitated and nothing calms him',
      'She’s withdrawn and hard to reach',
      'I want a simple tool that reliably helps',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Deeply-learned music and the memories attached to it are often preserved long into dementia. Favorite-era songs can lift mood, ease agitation, and open a door to connection and reminiscence — and doing it alongside the person (humming, tapping, swaying) improves engagement.',
    steps: [
      'Build a playlist from the music of their teens and twenties, plus any songs tied to their story.',
      'Cue it for the hard windows — sundowning, bathing, transitions — and for calm afternoons.',
      'Do it with them: hum along, tap the beat, sway, look at photos from that era.',
      'Note which songs reliably soothe, and keep those handy.',
    ],
    tool: { kind: 'playlist' },
    sources: [
      S('Dementia UK — Meaningful activities', 'https://www.dementiauk.org/news/meaningful-activities-for-a-person-with-dementia/'),
      S('Alzheimer’s Association — Activities', 'https://www.alz.org/help-support/caregiving/daily-care/activities'),
    ],
    related: ['calm-the-evening', 'capture-her-life-story', 'start-the-activity-for-them'],
  },
  {
    slug: 'daily-walk',
    n: 24,
    topic: 'activities',
    title: 'A short daily walk',
    summary: 'The most accessible activity there is — and one of the few that helps the person and you at the same time.',
    situations: [
      'He’s restless or sleeps poorly',
      'Her mood is low',
      'I never get a break or any exercise myself',
    ],
    stages: ['early', 'middle'],
    effort: 'habit',
    evidence: 'research',
    why: 'Regular physical activity — even short, light bouts — can lift mood, ease symptoms of depression, build strength and balance (reducing falls), and improve sleep. Walking is the most accessible option, and it benefits the caregiver’s stress too. Daytime activity also helps the body sleep at night.',
    steps: [
      'Add a short walk at the same time daily — ideally in the morning for the light.',
      'Match the distance and pace to current ability; finish vigorous activity at least four hours before bed.',
      'Make it pleasant and social, not a workout — somewhere familiar and safe.',
      'Count it as your break too.',
    ],
    tool: { kind: 'reminder' },
    sources: [
      S('Alzheimer’s Society (UK) — Exercise', 'https://www.alzheimers.org.uk/get-support/daily-living/exercise'),
      S('Caregiver physical activity (PMC)', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11690072/'),
    ],
    related: ['morning-light', 'anchor-the-day', 'protect-your-sleep'],
  },

  // ───────────────────────── SLEEP & EVENINGS ─────────────────────────
  {
    slug: 'morning-light',
    n: 25,
    topic: 'sleep',
    title: 'Get morning light to reset the body clock',
    summary: 'Night sleep is mostly won during the day. Bright light in the morning is one of your strongest levers.',
    situations: [
      'Day and night have flipped',
      'She naps all day and is up all night',
      'Nights are wrecking us both',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'Dementia damages the brain systems that regulate the sleep-wake cycle. Morning and daytime bright light is one of the strongest signals for a healthy circadian rhythm, and a full, active day reduces the daytime dozing that erodes the night.',
    steps: [
      'Get morning and daytime sunlight or bright light, every day.',
      'Keep naps short and earlier in the day so they don’t eat into the night.',
      'Fill the day with light activity and movement rather than long stretches dozing in a chair.',
      'Hold steady wake, meal, and bed times to reinforce the rhythm.',
    ],
    tool: { kind: 'reminder' },
    sources: [
      S('Alzheimer’s Association — Sleep changes', 'https://www.alz.org/alzheimers-dementia/treatments/for-sleep-changes'),
      S('Sleep Foundation — Alzheimer’s & sleep', 'https://www.sleepfoundation.org/physical-health/alzheimers-disease-and-sleep'),
    ],
    related: ['calm-the-evening', 'daily-walk', 'anchor-the-day'],
  },
  {
    slug: 'calm-the-evening',
    n: 26,
    topic: 'sleep',
    title: 'Calm the evening to ease sundowning',
    summary: 'Late-day agitation is often too much stimulation, fatigue, and fading light — not a reasoned complaint. Plan the calmest hours here.',
    situations: [
      'He gets agitated and confused every late afternoon',
      'Evenings spiral into distress',
      'She can’t settle at bedtime',
    ],
    stages: ['middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'Many people grow more confused, anxious, or agitated as light fades (“sundowning”), which then bleeds into a hard night. Managing the evening well — lower stimulation, more light to kill shadows, an identical routine — heads off both.',
    steps: [
      'As light fades, lower noise and stimulation but raise indoor lighting to cut shadows.',
      'Keep dinner early and calm; avoid caffeine and big decisions in the evening.',
      'Run the same soothing wind-down every night — wash, oral care, pajamas, gentle music or a back rub.',
      'Avoid TV, phones, and tablets right before bed; the content is arousing and the light delays sleep.',
    ],
    watchOut: ['Rule out treatable causes of poor sleep first — pain, depression, restless legs, sleep apnea, or a medication timed badly. Review with the doctor.'],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Sleep & sundowning', 'https://www.alz.org/help-support/caregiving/stages-behaviors/sleep-issues-sundowning'),
      S('Alzheimer’s Society (UK) — Healthy sleep tips', 'https://www.alzheimers.org.uk/about-dementia/stages-and-symptoms/healthy-sleep-tips'),
    ],
    related: ['morning-light', 'night-waking', 'cover-mirrors'],
  },
  {
    slug: 'night-waking',
    n: 27,
    topic: 'sleep',
    title: 'When they wake at night, stay low and calm',
    summary: 'Bright lights and “it’s the middle of the night” escalate. Keep it dim, check the obvious need, guide back to bed.',
    situations: [
      'She gets up and wanders at night',
      'He wakes confused and frightened',
      'Night waking is constant',
    ],
    stages: ['middle', 'late'],
    effort: 'moment',
    evidence: 'clinical',
    why: 'A person who wakes disoriented needs reassurance and the obvious need met — not an argument about the time. Bright lights, confrontation, or “go back to sleep, it’s 3am” tend to escalate and wake them further.',
    steps: [
      'Keep lighting dim; speak softly and reassure.',
      'Check the obvious unmet need — toilet, pain, hunger, thirst, cold, fear.',
      'Guide them back to bed without quizzing them or debating the time.',
      'Discourage staying in bed awake or turning on the TV, to keep bed linked to sleep.',
    ],
    watchOut: ['Sleep medications raise the risk of falls, fractures, and confusion in people with dementia and often don’t improve sleep. Antipsychotics carry an FDA black-box warning of increased stroke and death. Non-drug approaches first, always; involve the prescriber before any medication.'],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Association — Sleep changes', 'https://www.alz.org/alzheimers-dementia/treatments/for-sleep-changes'),
      S('Alzheimer’s Society (UK) — Healthy sleep tips', 'https://www.alzheimers.org.uk/about-dementia/stages-and-symptoms/healthy-sleep-tips'),
    ],
    related: ['calm-the-evening', 'light-the-path', 'protect-your-sleep'],
  },

  // ───────────────────────── HOME & SAFETY ─────────────────────────
  {
    slug: 'mark-the-edges',
    n: 28,
    topic: 'home',
    title: 'Mark real step edges and remove confusing patterns',
    summary: 'Dementia distorts depth and pattern: a flooring change can read as a step, a shiny floor as water, a busy rug as a hole.',
    situations: [
      'He hesitates or freezes at thresholds and steps',
      'She steps oddly over flat floors or avoids certain spots',
      'I want to prevent a fall before it happens',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Impaired depth perception makes a carpet-to-tile change look like a step; misperceived patterns make speckled floors look like dirt or holes and shiny floors look wet. The fix is to remove the false cues and clearly mark the real hazards.',
    steps: [
      'Mark real step edges with a strip of bright, contrasting tape; add handrails on both sides of stairs.',
      'Avoid flooring transitions and busy patterns; choose matte, plain, mid-tone flooring.',
      'Remove or tape down rugs, especially patterned ones.',
      'Note: a plain dark mat can be misread as a hole — useful deliberately to deter an exit, but remove it where you want them to walk freely.',
    ],
    tool: { kind: 'video' },
    sources: [
      S('NIA — Home safety / falls room by room', 'https://www.nia.nih.gov/health/falls-and-falls-prevention/preventing-falls-home-room-room'),
      S('Alzheimer’s Society (UK) — Dementia-friendly home (PDF)', 'https://www.alzheimers.org.uk/sites/default/files/migrate/downloads/making_your_home_dementia_friendly.pdf'),
    ],
    related: ['add-contrast', 'make-the-toilet-findable', 'reduce-wandering'],
  },
  {
    slug: 'add-contrast',
    n: 29,
    topic: 'home',
    title: 'Add contrast so they can see what matters',
    summary: 'When the brain can’t distinguish similar tones, a white toilet on a pale floor disappears. Make key things pop.',
    situations: [
      'He can’t find the toilet / misses the plate',
      'She seems to “lose” objects that are right there',
      'Meals and bathroom trips are harder than they should be',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Loss of visual contrast sensitivity means similar tones blend together — a white toilet on a pale floor, food on a white plate. High contrast restores what the eyes can no longer separate, supporting independence in eating, toileting, and getting around.',
    steps: [
      'Use a brightly contrasting toilet seat, and contrasting grab bars, switch plates, and door frames.',
      'Serve food on a plain plate that contrasts with both the food and the table.',
      'Add contrast at the edges of counters, handrails, and steps.',
      'Boost overall lighting — aim for brighter, even light, roughly twice normal.',
    ],
    tool: { kind: 'checklist' },
    sources: [
      S('Alzheimer’s Association — Home safety', 'https://www.alz.org/help-support/caregiving/safety/home-safety'),
      S('Dementia Alliance International — Colour & pattern', 'https://dementiaallianceinternational.org/blog/colour-and-pattern-in-dementia-care-environments'),
    ],
    related: ['make-the-toilet-findable', 'one-food-at-a-time', 'mark-the-edges'],
  },
  {
    slug: 'make-the-toilet-findable',
    n: 30,
    topic: 'home',
    title: 'Make the toilet easy to find',
    summary: 'A surprising share of accidents is simply not finding or recognizing the toilet in time. Make it obvious, day and night.',
    situations: [
      'She can’t locate the bathroom',
      'He doesn’t recognize the toilet for what it is',
      'Night-time accidents on the way to the bathroom',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Disorientation means the person may not find the bathroom or recognize the toilet’s purpose. Visual signposting and a lit path turn a confusing search into an obvious one, preventing accidents and the distress around them.',
    steps: [
      'Keep the bathroom door open with the toilet visible; add a sign or a picture of a toilet on the door.',
      'Use a contrasting toilet seat so it stands out.',
      'Light the path from bed to bathroom with motion night-lights.',
      'Position the bed, if you can, so the toilet is in view at night.',
    ],
    tool: { kind: 'checklist' },
    sources: [
      S('Alzheimer’s Association — Incontinence', 'https://www.alz.org/help-support/caregiving/daily-care/incontinence'),
      S('NHS — Make your home dementia friendly', 'https://www.nhs.uk/conditions/dementia/living-with-dementia/home-environment/'),
    ],
    related: ['scheduled-toileting', 'add-contrast', 'light-the-path'],
  },
  {
    slug: 'cover-mirrors',
    n: 31,
    topic: 'home',
    title: 'Cover mirrors and night windows',
    summary: 'A reflection can read as a stranger in the house. If mirrors frighten or agitate, simply remove the trigger.',
    situations: [
      'She’s frightened by “someone” in the mirror',
      'He talks to or argues with his reflection',
      'Dark windows at night cause distress',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'When the brain can’t place a reflection, a mirror or a dark night window can look like a stranger watching — frightening and agitating. The simplest fix is to remove the misread image rather than explain it.',
    steps: [
      'Cover or remove mirrors that cause distress.',
      'Close curtains and blinds before dark so night windows don’t reflect.',
      'Reduce other reflective surfaces and shiny floors where they cause confusion.',
      'For visual hallucinations (common in Lewy body dementia), photo-audit the room and remove triggers — hanging clothes, patterns, clutter — and even out the lighting.',
    ],
    tool: { kind: 'video' },
    sources: [
      S('BrightFocus — Dementia-friendly home', 'https://www.brightfocus.org/resource/making-your-home-dementia-friendly/'),
      S('Lewy body visual hallucinations (PMC)', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10978580/'),
    ],
    related: ['calm-the-evening', 'reduce-wandering'],
  },
  {
    slug: 'reduce-wandering',
    n: 32,
    topic: 'home',
    title: 'Lower the risk at exits',
    summary: 'Exit-seeking is common and dangerous. Make leaving harder to notice and act on — and prepare for if it happens.',
    situations: [
      'He tries to leave the house',
      'I’m terrified she’ll get out and get lost',
      'Exit-seeking spikes in the late afternoon',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Wandering and exit-seeking put a person at real risk of getting lost. Reducing the conflict at the environmental level — making the door less noticeable and adding alarms and tracking — is safer and less distressing than repeated arguments about staying in.',
    steps: [
      'Add door and window alarms so you’re alerted to an exit attempt.',
      'Make exit doors less obvious — locks placed high or low and out of the usual line of sight, a disguised-door cover, or a black threshold strip read as a barrier.',
      'Use a GPS tracker or wearable with geofencing for outings and as backup.',
      'Address the driver — exit-seeking often rises with sundowning, boredom, or an unmet need; calm the evening and fill the day.',
    ],
    watchOut: ['Don’t block exits in a way that creates a fire-safety hazard. Keep a recent photo and key details ready in case you ever need to report someone missing.'],
    tool: { kind: 'checklist' },
    sources: [
      S('Alzheimer’s Association — Home safety', 'https://www.alz.org/help-support/caregiving/safety/home-safety'),
      S('NIA — Home safety tips', 'https://www.nia.nih.gov/health/safety/alzheimers-caregiving-home-safety-tips'),
    ],
    related: ['calm-the-evening', 'cover-mirrors', 'mark-the-edges'],
  },
  {
    slug: 'light-the-path',
    n: 33,
    topic: 'home',
    title: 'Light the path and the night',
    summary: 'Many night falls and much night fear come down to darkness and shadows. Cheap lighting fixes a lot.',
    situations: [
      'Night-time falls or near-misses',
      'He’s frightened or disoriented when he wakes',
      'Shadows seem to confuse her in the evening',
    ],
    stages: ['middle', 'late'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'A dark, shadowed home at night drives both falls and fear for someone who wakes disoriented. Motion night-lights, a clear path, and a way to tell night from day reduce both — and a comfortably cool, dark, quiet bedroom supports sleep.',
    steps: [
      'Add motion night-lights along the path from bed to bathroom.',
      'Keep the bedroom dark, quiet, and comfortably cool (around the mid-60s°F / 18°C).',
      'Consider a dementia-friendly day/night clock that shows whether it’s night, for someone who wakes disoriented.',
      'In the evening, raise indoor lighting to cut the shadows that fuel sundowning.',
    ],
    tool: { kind: 'checklist' },
    sources: [
      S('Alzheimer’s Association — Sleep changes', 'https://www.alz.org/alzheimers-dementia/treatments/for-sleep-changes'),
      S('NIA — Home safety tips', 'https://www.nia.nih.gov/health/safety/alzheimers-caregiving-home-safety-tips'),
    ],
    related: ['night-waking', 'calm-the-evening', 'make-the-toilet-findable'],
  },

  // ───────────────────────── CAREGIVER ─────────────────────────
  {
    slug: 'capture-her-life-story',
    n: 34,
    topic: 'caregiver',
    title: 'Capture their life story now',
    summary: 'Turn “who they were before” from a lonely thing in your head into a shared, reusable document — while they can still help write it.',
    situations: [
      'I’m the only one who remembers who she really is',
      'New aides and doctors treat him like a patient, not a person',
      'I want to do something meaningful together early on',
    ],
    stages: ['early', 'middle'],
    effort: 'setup',
    evidence: 'clinical',
    why: 'Knowing a person’s history, achievements, and preferences lets everyone treat them as an individual, which reduces distress — and handed to a hospital or care home, it helps staff care well from day one. It also lifts the invisible burden of being the sole keeper of who they were, and powers reminiscence and redirection. Capture it early, while they can still contribute their own voice.',
    steps: [
      'Use an established template so it’s familiar to clinicians — the Alzheimer’s Society’s “This is me” or the NHS “Getting to know me.”',
      'Capture identity (name they prefer, history, key people, career, faith), preferences (what soothes, favorite music and foods, routines), and care needs.',
      'Record some of it in their own words — by voice or video. This is the irreplaceable part.',
      'Make it an activity with them, not a dossier about them; keep a short printable summary for hospital or ER, and share access across the family.',
    ],
    tool: { kind: 'printable' },
    sources: [
      S('Alzheimer’s Society (UK) — “This is me”', 'https://www.alzheimers.org.uk/get-support/publications-factsheets/this-is-me'),
      S('Age UK — Life story work', 'https://www.ageuk.org.uk/sheffield/our-services/home-care-toolkit/practical-ideas-to-support-a-person-with-dementia/life-story-work/'),
    ],
    related: ['favorite-era-playlist', 'talk-to-me-not-about-me', 'hold-both-and'],
  },
  {
    slug: 'hold-both-and',
    n: 35,
    topic: 'caregiver',
    title: 'Hold “both/and” instead of waiting for closure',
    summary: 'You’re grieving someone who is still alive. The skill isn’t resolving that — it’s carrying two truths at once.',
    situations: [
      'I’m grieving my mother while she’s still here',
      'I feel love and grief, relief and guilt, all at once',
      'People say “but she’s still here” and it doesn’t help',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'This is ambiguous loss (Pauline Boss): a loss without closure, where the person is physically present but psychologically changing — “the long goodbye.” Because no one has died, the grief often isn’t socially recognized, which isolates you. Boss’s central move is to stop searching for a perfect resolution and hold two truths at once.',
    steps: [
      'Name it: this is grief, and it’s allowed — anticipatory grief and ambiguous loss are real.',
      'Practice both/and: she is both here and gone; both my mother and someone who needs mothering; I feel both love and grief.',
      'Adjust your idea of mastery — you can’t fix this; control what you can and let go of the rest.',
      'Externalize the illness for yourself too: your frustration and grief are not failures of love.',
    ],
    watchOut: ['If hopelessness or emptiness lasts more than two weeks, basic tasks slip, or you’re using alcohol or medication to cope, reach out to a clinician — these are signals to act, not weakness. If you ever have thoughts of self-harm or of not being able to go on, treat it as urgent and get help now (in the US, call or text 988).'],
    tool: { kind: 'practice' },
    sources: [
      S('Family Caregiver Alliance — Ambiguous loss', 'https://www.caregiver.org/resource/caregiving-and-ambiguous-loss/'),
      S('Alzheimer’s Association — Grief & loss', 'https://www.alz.org/help-support/caregiving/caregiver-health/grief-loss-as-alzheimers-progresses'),
    ],
    related: ['protect-your-sleep', 'externalize-the-disease', 'capture-her-life-story'],
  },
  {
    slug: 'protect-your-sleep',
    n: 36,
    topic: 'caregiver',
    title: 'Protect your own sleep and take respite',
    summary: 'Respite isn’t a luxury — it’s maintenance. Broken nights and no breaks are how caregivers reach crisis.',
    situations: [
      'I’m exhausted and running on empty',
      'I never get a full night’s sleep',
      'I feel guilty even thinking about a break',
    ],
    stages: ['early', 'middle', 'late'],
    effort: 'habit',
    evidence: 'clinical',
    why: 'Caregiver sleep loss is a major, often-hidden harm, and broken nights are one of the most common reasons families reach crisis or move toward residential care. Planned breaks while the person is safely cared for are essential maintenance — and sharing the load protects both of you.',
    steps: [
      'Treat respite as essential: arrange planned breaks where the person is safely cared for, so broken nights can be shared.',
      'Protect your own sleep deliberately — your own wind-down, no screens in bed; aim for a proper night at least every third night.',
      'Distribute the work — advocacy, decisions, memory-keeping — across family rather than carrying it alone.',
      'Use peer communities and the national helplines (in the US, the Alzheimer’s Association 24/7 Helpline, 800-272-3900).',
    ],
    watchOut: ['Watch for burnout — fatigue rest doesn’t fix, constant irritability, hopelessness, withdrawing from people, leaning on alcohol or caffeine to cope. These are reasons to get support now.'],
    tool: { kind: 'reminder' },
    sources: [
      S('Alzheimer’s Association — Caregiver stress', 'https://www.alz.org/help-support/caregiving/caregiver-health/caregiver-stress'),
      S('Sleep Foundation — Alzheimer’s & sleep', 'https://www.sleepfoundation.org/physical-health/alzheimers-disease-and-sleep'),
    ],
    related: ['hold-both-and', 'morning-light', 'night-waking'],
  },
]

// Common "what's hardest right now" entry points → maps to a search query
export const QUICK_ENTRIES = [
  { label: 'Won’t bathe', q: 'bath', icon: 'droplet' },
  { label: 'Won’t eat', q: 'eat', icon: 'utensils' },
  { label: 'Up at night', q: 'night sleep', icon: 'moon' },
  { label: 'Agitated late in the day', q: 'sundowning agitated evening', icon: 'sunset' },
  { label: 'Repeating & confusion', q: 'repeats question confused', icon: 'repeat' },
  { label: 'Refusing care or meds', q: 'refuses medication', icon: 'shield' },
  { label: 'Wandering', q: 'wandering exit leave', icon: 'compass' },
  { label: 'I’m grieving / burning out', q: 'grief burnout caregiver sleep', icon: 'heart' },
]

export function topicById(id) { return TOPICS.find(t => t.id === id) }
export function stageLabel(id) { return (STAGES.find(s => s.id === id) || {}).label || id }
export function effortById(id) { return EFFORTS.find(e => e.id === id) }
export function evidenceById(id) { return EVIDENCE.find(e => e.id === id) }
